spring:
  application:
    name: "mdc-replicator"

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{x-request-id:-}] "
  include-application-name: false
management:
  observations:
    http:
      client:
        requests:
          name: "http.client.requests"
      server:
        requests:
          name: "http.server.requests"
  tracing:
    enabled: true
    sampling:
      probability: 1
    baggage:
      enabled: true
      correlation:
        enabled: true
        fields: x-request-id
      remote-fields: x-request-id
    propagation:
      type: w3c, b3_multi, b3
